# Site settings
title: Project Responsive
email: paul@projectresponsive.com
description: "Hello, it's me"
baseurl: 
url: "http://projectresponsive.com"
tagline: "Paul Kenneth Kent"
twitter_username: paulkennehtkent
github_username:  paulkennethkent
collections:
 projects:
  output: true
  permalink: /projects/:title

# Build settings
markdown: kramdown
permalink: /blog/:title


#gems
gems:
- susy
- breakpoint
